"""create comments

Revision ID: 2348f9aa191f
Revises: b41c7d9e2f05
Create Date: 2026-10-02 10:57:46.165219

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2348f9aa191f'
down_revision: str | None = 'b41c7d9e2f05'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('world_x', sa.Double(), nullable=False),
    sa.Column('world_y', sa.Double(), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('resolved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # raw string：必須與 app/models/comment.py 的 CheckConstraint 逐字相同。
    sa.CheckConstraint(r"content ~ '[^ \t\n\r\f\v]'", name=op.f('ck_comments_content_not_blank')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_comments_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_comments_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index('ix_comments_project_id_created_at', 'comments', ['project_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_project_id_created_at', table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
